// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Instance struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InstanceType         string   `protobuf:"bytes,2,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	Ecu                  float32  `protobuf:"fixed32,3,opt,name=ecu,proto3" json:"ecu,omitempty"`
	Memory               float32  `protobuf:"fixed32,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Network              string   `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Price                string   `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Instance) GetInstanceType() string {
	if m != nil {
		return m.InstanceType
	}
	return ""
}

func (m *Instance) GetEcu() float32 {
	if m != nil {
		return m.Ecu
	}
	return 0
}

func (m *Instance) GetMemory() float32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Instance) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Instance) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

type Instances struct {
	Instances            []*Instance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Instances) Reset()         { *m = Instances{} }
func (m *Instances) String() string { return proto.CompactTextString(m) }
func (*Instances) ProtoMessage()    {}
func (*Instances) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Instances) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instances.Unmarshal(m, b)
}
func (m *Instances) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instances.Marshal(b, m, deterministic)
}
func (m *Instances) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instances.Merge(m, src)
}
func (m *Instances) XXX_Size() int {
	return xxx_messageInfo_Instances.Size(m)
}
func (m *Instances) XXX_DiscardUnknown() {
	xxx_messageInfo_Instances.DiscardUnknown(m)
}

var xxx_messageInfo_Instances proto.InternalMessageInfo

func (m *Instances) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterType((*Instance)(nil), "api.Instance")
	proto.RegisterType((*Instances)(nil), "api.Instances")
	proto.RegisterType((*SearchRequest)(nil), "api.SearchRequest")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0x5f, 0x4b, 0xfb, 0x30,
	0x14, 0xa5, 0xeb, 0xd6, 0xdf, 0xaf, 0x57, 0x27, 0x72, 0x11, 0x09, 0x3e, 0x8d, 0x89, 0x30, 0x50,
	0xd6, 0xb9, 0xfa, 0xe0, 0xab, 0xbe, 0xf9, 0x22, 0xa3, 0x0a, 0x82, 0x2f, 0x23, 0x66, 0x97, 0x19,
	0x5c, 0x9a, 0x2c, 0x49, 0x91, 0x7e, 0x18, 0xbf, 0xab, 0x34, 0x6d, 0x91, 0xbd, 0x9d, 0x3f, 0x37,
	0xf7, 0xe4, 0x1e, 0x48, 0xb9, 0x91, 0x73, 0x63, 0xb5, 0xd7, 0x18, 0x73, 0x23, 0xa7, 0x3f, 0x11,
	0xfc, 0x7f, 0x2a, 0x9d, 0xe7, 0xa5, 0x20, 0x44, 0x18, 0x96, 0x5c, 0x11, 0x8b, 0x26, 0xd1, 0x2c,
	0x2d, 0x02, 0xc6, 0x4b, 0x18, 0xcb, 0xce, 0x5f, 0xfb, 0xda, 0x10, 0x1b, 0x04, 0xf3, 0xb8, 0x17,
	0x5f, 0x6b, 0x43, 0x78, 0x0a, 0x31, 0x89, 0x8a, 0xc5, 0x93, 0x68, 0x36, 0x28, 0x1a, 0x88, 0xe7,
	0x90, 0x28, 0x52, 0xda, 0xd6, 0x6c, 0x18, 0xc4, 0x8e, 0x21, 0x83, 0x7f, 0x25, 0xf9, 0x6f, 0x6d,
	0xbf, 0xd8, 0x28, 0x2c, 0xea, 0x29, 0x9e, 0xc1, 0xc8, 0x58, 0x29, 0x88, 0x25, 0x41, 0x6f, 0xc9,
	0xf4, 0x1e, 0xd2, 0xfe, 0x7b, 0x0e, 0xaf, 0x21, 0xed, 0x63, 0x1d, 0x8b, 0x26, 0xf1, 0xec, 0x68,
	0x39, 0x9e, 0x37, 0x07, 0xf5, 0x23, 0xc5, 0x9f, 0x3f, 0xbd, 0x82, 0xf1, 0x0b, 0x71, 0x2b, 0x3e,
	0x0b, 0xda, 0x57, 0xe4, 0x7c, 0x13, 0xb0, 0xaf, 0xc8, 0xd6, 0xdd, 0x79, 0x2d, 0x59, 0xe6, 0x10,
	0x3f, 0x18, 0x89, 0x37, 0x90, 0xb4, 0xd3, 0x88, 0x61, 0xe3, 0xc1, 0xd3, 0x8b, 0x93, 0x83, 0x14,
	0xf7, 0x98, 0xbf, 0xdf, 0x0a, 0xb5, 0xc9, 0x16, 0x77, 0x8b, 0xf5, 0x56, 0xef, 0x78, 0xb9, 0x7d,
	0xe3, 0x4e, 0xad, 0x9a, 0x56, 0xdd, 0xb3, 0xf6, 0x2b, 0x4b, 0x42, 0x2b, 0x23, 0x77, 0xb4, 0xc9,
	0x42, 0xd5, 0x2e, 0xe3, 0x46, 0x7e, 0x24, 0x01, 0xe7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x13,
	0xca, 0xff, 0x5f, 0x83, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*Instances, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*Instances, error) {
	out := new(Instances)
	err := c.cc.Invoke(ctx, "/api.Api/SearchInDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	Search(context.Context, *SearchRequest) (*Instances, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) Search(ctx context.Context, req *SearchRequest) (*Instances, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchInDB not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/SearchInDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchInDB",
			Handler:    _Api_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
