// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MagicTableType int32

const (
	MagicTableType_TestModel   MagicTableType = 0
	MagicTableType_DomainModel MagicTableType = 1
	MagicTableType_PluginModel MagicTableType = 2
)

var MagicTableType_name = map[int32]string{
	0: "TestModel",
	1: "DomainModel",
	2: "PluginModel",
}

var MagicTableType_value = map[string]int32{
	"TestModel":   0,
	"DomainModel": 1,
	"PluginModel": 2,
}

func (x MagicTableType) String() string {
	return proto.EnumName(MagicTableType_name, int32(x))
}

func (MagicTableType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type MagicTableColumnDataType int32

const (
	MagicTableColumnDataType_String MagicTableColumnDataType = 0
	MagicTableColumnDataType_Int    MagicTableColumnDataType = 1
	MagicTableColumnDataType_Float  MagicTableColumnDataType = 2
)

var MagicTableColumnDataType_name = map[int32]string{
	0: "String",
	1: "Int",
	2: "Float",
}

var MagicTableColumnDataType_value = map[string]int32{
	"String": 0,
	"Int":    1,
	"Float":  2,
}

func (x MagicTableColumnDataType) String() string {
	return proto.EnumName(MagicTableColumnDataType_name, int32(x))
}

func (MagicTableColumnDataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

type MagicTableColumnPresentationType int32

const (
	MagicTableColumnPresentationType_Simple  MagicTableColumnPresentationType = 0
	MagicTableColumnPresentationType_Sprintf MagicTableColumnPresentationType = 1
)

var MagicTableColumnPresentationType_name = map[int32]string{
	0: "Simple",
	1: "Sprintf",
}

var MagicTableColumnPresentationType_value = map[string]int32{
	"Simple":  0,
	"Sprintf": 1,
}

func (x MagicTableColumnPresentationType) String() string {
	return proto.EnumName(MagicTableColumnPresentationType_name, int32(x))
}

func (MagicTableColumnPresentationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

type NewOrUpdateTestDomainUpdateType int32

const (
	NewOrUpdateTestDomainUpdateType_New    NewOrUpdateTestDomainUpdateType = 0
	NewOrUpdateTestDomainUpdateType_Update NewOrUpdateTestDomainUpdateType = 1
)

var NewOrUpdateTestDomainUpdateType_name = map[int32]string{
	0: "New",
	1: "Update",
}

var NewOrUpdateTestDomainUpdateType_value = map[string]int32{
	"New":    0,
	"Update": 1,
}

func (x NewOrUpdateTestDomainUpdateType) String() string {
	return proto.EnumName(NewOrUpdateTestDomainUpdateType_name, int32(x))
}

func (NewOrUpdateTestDomainUpdateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

type Instance struct {
	UniqueId             int64    `protobuf:"varint,1,opt,name=UniqueId,proto3" json:"UniqueId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	InstanceType         string   `protobuf:"bytes,3,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	Ecu                  float32  `protobuf:"fixed32,4,opt,name=ecu,proto3" json:"ecu,omitempty"`
	Memory               float32  `protobuf:"fixed32,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Network              string   `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	Price                string   `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetUniqueId() int64 {
	if m != nil {
		return m.UniqueId
	}
	return 0
}

func (m *Instance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Instance) GetInstanceType() string {
	if m != nil {
		return m.InstanceType
	}
	return ""
}

func (m *Instance) GetEcu() float32 {
	if m != nil {
		return m.Ecu
	}
	return 0
}

func (m *Instance) GetMemory() float32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Instance) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Instance) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

type Instances struct {
	Instances            []*Instance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Instances) Reset()         { *m = Instances{} }
func (m *Instances) String() string { return proto.CompactTextString(m) }
func (*Instances) ProtoMessage()    {}
func (*Instances) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Instances) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instances.Unmarshal(m, b)
}
func (m *Instances) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instances.Marshal(b, m, deterministic)
}
func (m *Instances) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instances.Merge(m, src)
}
func (m *Instances) XXX_Size() int {
	return xxx_messageInfo_Instances.Size(m)
}
func (m *Instances) XXX_DiscardUnknown() {
	xxx_messageInfo_Instances.DiscardUnknown(m)
}

var xxx_messageInfo_Instances proto.InternalMessageInfo

func (m *Instances) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type TimeMessage struct {
	TimeString           string   `protobuf:"bytes,1,opt,name=timeString,proto3" json:"timeString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeMessage) Reset()         { *m = TimeMessage{} }
func (m *TimeMessage) String() string { return proto.CompactTextString(m) }
func (*TimeMessage) ProtoMessage()    {}
func (*TimeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *TimeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeMessage.Unmarshal(m, b)
}
func (m *TimeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeMessage.Marshal(b, m, deterministic)
}
func (m *TimeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeMessage.Merge(m, src)
}
func (m *TimeMessage) XXX_Size() int {
	return xxx_messageInfo_TimeMessage.Size(m)
}
func (m *TimeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TimeMessage proto.InternalMessageInfo

func (m *TimeMessage) GetTimeString() string {
	if m != nil {
		return m.TimeString
	}
	return ""
}

type EmptyParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParameter) Reset()         { *m = EmptyParameter{} }
func (m *EmptyParameter) String() string { return proto.CompactTextString(m) }
func (*EmptyParameter) ProtoMessage()    {}
func (*EmptyParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *EmptyParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParameter.Unmarshal(m, b)
}
func (m *EmptyParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParameter.Marshal(b, m, deterministic)
}
func (m *EmptyParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParameter.Merge(m, src)
}
func (m *EmptyParameter) XXX_Size() int {
	return xxx_messageInfo_EmptyParameter.Size(m)
}
func (m *EmptyParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParameter.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParameter proto.InternalMessageInfo

type MagicTableMetadataRequest struct {
	MagicTableMetadataType MagicTableType `protobuf:"varint,1,opt,name=MagicTableMetadataType,proto3,enum=api.MagicTableType" json:"MagicTableMetadataType,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}       `json:"-"`
	XXX_unrecognized       []byte         `json:"-"`
	XXX_sizecache          int32          `json:"-"`
}

func (m *MagicTableMetadataRequest) Reset()         { *m = MagicTableMetadataRequest{} }
func (m *MagicTableMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*MagicTableMetadataRequest) ProtoMessage()    {}
func (*MagicTableMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *MagicTableMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MagicTableMetadataRequest.Unmarshal(m, b)
}
func (m *MagicTableMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MagicTableMetadataRequest.Marshal(b, m, deterministic)
}
func (m *MagicTableMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MagicTableMetadataRequest.Merge(m, src)
}
func (m *MagicTableMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_MagicTableMetadataRequest.Size(m)
}
func (m *MagicTableMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MagicTableMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MagicTableMetadataRequest proto.InternalMessageInfo

func (m *MagicTableMetadataRequest) GetMagicTableMetadataType() MagicTableType {
	if m != nil {
		return m.MagicTableMetadataType
	}
	return MagicTableType_TestModel
}

type MagicTableMetadataRespons struct {
	MagicTableColumnsMetadata []*MagicTableColumnMetadata `protobuf:"bytes,1,rep,name=MagicTableColumnsMetadata,proto3" json:"MagicTableColumnsMetadata,omitempty"`
	SearchbarIsVisible        bool                        `protobuf:"varint,2,opt,name=SearchbarIsVisible,proto3" json:"SearchbarIsVisible,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                    `json:"-"`
	XXX_unrecognized          []byte                      `json:"-"`
	XXX_sizecache             int32                       `json:"-"`
}

func (m *MagicTableMetadataRespons) Reset()         { *m = MagicTableMetadataRespons{} }
func (m *MagicTableMetadataRespons) String() string { return proto.CompactTextString(m) }
func (*MagicTableMetadataRespons) ProtoMessage()    {}
func (*MagicTableMetadataRespons) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *MagicTableMetadataRespons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MagicTableMetadataRespons.Unmarshal(m, b)
}
func (m *MagicTableMetadataRespons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MagicTableMetadataRespons.Marshal(b, m, deterministic)
}
func (m *MagicTableMetadataRespons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MagicTableMetadataRespons.Merge(m, src)
}
func (m *MagicTableMetadataRespons) XXX_Size() int {
	return xxx_messageInfo_MagicTableMetadataRespons.Size(m)
}
func (m *MagicTableMetadataRespons) XXX_DiscardUnknown() {
	xxx_messageInfo_MagicTableMetadataRespons.DiscardUnknown(m)
}

var xxx_messageInfo_MagicTableMetadataRespons proto.InternalMessageInfo

func (m *MagicTableMetadataRespons) GetMagicTableColumnsMetadata() []*MagicTableColumnMetadata {
	if m != nil {
		return m.MagicTableColumnsMetadata
	}
	return nil
}

func (m *MagicTableMetadataRespons) GetSearchbarIsVisible() bool {
	if m != nil {
		return m.SearchbarIsVisible
	}
	return false
}

type MagicTableColumnMetadata struct {
	ColumnHeaderName       string                           `protobuf:"bytes,1,opt,name=ColumnHeaderName,proto3" json:"ColumnHeaderName,omitempty"`
	ColumnDataName         string                           `protobuf:"bytes,2,opt,name=ColumnDataName,proto3" json:"ColumnDataName,omitempty"`
	ColumnDataType         MagicTableColumnDataType         `protobuf:"varint,3,opt,name=ColumnDataType,proto3,enum=api.MagicTableColumnDataType" json:"ColumnDataType,omitempty"`
	Sortable               bool                             `protobuf:"varint,4,opt,name=Sortable,proto3" json:"Sortable,omitempty"`
	FormatPresentationType MagicTableColumnPresentationType `protobuf:"varint,5,opt,name=FormatPresentationType,proto3,enum=api.MagicTableColumnPresentationType" json:"FormatPresentationType,omitempty"`
	ShouldBeVisible        bool                             `protobuf:"varint,6,opt,name=ShouldBeVisible,proto3" json:"ShouldBeVisible,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                         `json:"-"`
	XXX_unrecognized       []byte                           `json:"-"`
	XXX_sizecache          int32                            `json:"-"`
}

func (m *MagicTableColumnMetadata) Reset()         { *m = MagicTableColumnMetadata{} }
func (m *MagicTableColumnMetadata) String() string { return proto.CompactTextString(m) }
func (*MagicTableColumnMetadata) ProtoMessage()    {}
func (*MagicTableColumnMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *MagicTableColumnMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MagicTableColumnMetadata.Unmarshal(m, b)
}
func (m *MagicTableColumnMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MagicTableColumnMetadata.Marshal(b, m, deterministic)
}
func (m *MagicTableColumnMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MagicTableColumnMetadata.Merge(m, src)
}
func (m *MagicTableColumnMetadata) XXX_Size() int {
	return xxx_messageInfo_MagicTableColumnMetadata.Size(m)
}
func (m *MagicTableColumnMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_MagicTableColumnMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_MagicTableColumnMetadata proto.InternalMessageInfo

func (m *MagicTableColumnMetadata) GetColumnHeaderName() string {
	if m != nil {
		return m.ColumnHeaderName
	}
	return ""
}

func (m *MagicTableColumnMetadata) GetColumnDataName() string {
	if m != nil {
		return m.ColumnDataName
	}
	return ""
}

func (m *MagicTableColumnMetadata) GetColumnDataType() MagicTableColumnDataType {
	if m != nil {
		return m.ColumnDataType
	}
	return MagicTableColumnDataType_String
}

func (m *MagicTableColumnMetadata) GetSortable() bool {
	if m != nil {
		return m.Sortable
	}
	return false
}

func (m *MagicTableColumnMetadata) GetFormatPresentationType() MagicTableColumnPresentationType {
	if m != nil {
		return m.FormatPresentationType
	}
	return MagicTableColumnPresentationType_Simple
}

func (m *MagicTableColumnMetadata) GetShouldBeVisible() bool {
	if m != nil {
		return m.ShouldBeVisible
	}
	return false
}

type ListTestDomainRespons struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Guid                 string   `protobuf:"bytes,2,opt,name=Guid,proto3" json:"Guid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	ReadyForUse          bool     `protobuf:"varint,5,opt,name=ReadyForUse,proto3" json:"ReadyForUse,omitempty"`
	Activated            bool     `protobuf:"varint,6,opt,name=Activated,proto3" json:"Activated,omitempty"`
	Deleted              bool     `protobuf:"varint,7,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	UpdateTimestamp      string   `protobuf:"bytes,8,opt,name=UpdateTimestamp,proto3" json:"UpdateTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTestDomainRespons) Reset()         { *m = ListTestDomainRespons{} }
func (m *ListTestDomainRespons) String() string { return proto.CompactTextString(m) }
func (*ListTestDomainRespons) ProtoMessage()    {}
func (*ListTestDomainRespons) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *ListTestDomainRespons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTestDomainRespons.Unmarshal(m, b)
}
func (m *ListTestDomainRespons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTestDomainRespons.Marshal(b, m, deterministic)
}
func (m *ListTestDomainRespons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTestDomainRespons.Merge(m, src)
}
func (m *ListTestDomainRespons) XXX_Size() int {
	return xxx_messageInfo_ListTestDomainRespons.Size(m)
}
func (m *ListTestDomainRespons) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTestDomainRespons.DiscardUnknown(m)
}

var xxx_messageInfo_ListTestDomainRespons proto.InternalMessageInfo

func (m *ListTestDomainRespons) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListTestDomainRespons) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *ListTestDomainRespons) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListTestDomainRespons) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ListTestDomainRespons) GetReadyForUse() bool {
	if m != nil {
		return m.ReadyForUse
	}
	return false
}

func (m *ListTestDomainRespons) GetActivated() bool {
	if m != nil {
		return m.Activated
	}
	return false
}

func (m *ListTestDomainRespons) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *ListTestDomainRespons) GetUpdateTimestamp() string {
	if m != nil {
		return m.UpdateTimestamp
	}
	return ""
}

type ListTestDomainsRespons struct {
	MyListTestDomainsRespons []*ListTestDomainRespons `protobuf:"bytes,1,rep,name=MyListTestDomainsRespons,proto3" json:"MyListTestDomainsRespons,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                 `json:"-"`
	XXX_unrecognized         []byte                   `json:"-"`
	XXX_sizecache            int32                    `json:"-"`
}

func (m *ListTestDomainsRespons) Reset()         { *m = ListTestDomainsRespons{} }
func (m *ListTestDomainsRespons) String() string { return proto.CompactTextString(m) }
func (*ListTestDomainsRespons) ProtoMessage()    {}
func (*ListTestDomainsRespons) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *ListTestDomainsRespons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTestDomainsRespons.Unmarshal(m, b)
}
func (m *ListTestDomainsRespons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTestDomainsRespons.Marshal(b, m, deterministic)
}
func (m *ListTestDomainsRespons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTestDomainsRespons.Merge(m, src)
}
func (m *ListTestDomainsRespons) XXX_Size() int {
	return xxx_messageInfo_ListTestDomainsRespons.Size(m)
}
func (m *ListTestDomainsRespons) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTestDomainsRespons.DiscardUnknown(m)
}

var xxx_messageInfo_ListTestDomainsRespons proto.InternalMessageInfo

func (m *ListTestDomainsRespons) GetMyListTestDomainsRespons() []*ListTestDomainRespons {
	if m != nil {
		return m.MyListTestDomainsRespons
	}
	return nil
}

type NewOrUpdateTestDomainRequest struct {
	NewOrUpdate               NewOrUpdateTestDomainUpdateType `protobuf:"varint,1,opt,name=NewOrUpdate,proto3,enum=api.NewOrUpdateTestDomainUpdateType" json:"NewOrUpdate,omitempty"`
	NewOrUpdateTestDomainData *NewOrUpdateTestDomainData      `protobuf:"bytes,2,opt,name=NewOrUpdateTestDomainData,proto3" json:"NewOrUpdateTestDomainData,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                        `json:"-"`
	XXX_unrecognized          []byte                          `json:"-"`
	XXX_sizecache             int32                           `json:"-"`
}

func (m *NewOrUpdateTestDomainRequest) Reset()         { *m = NewOrUpdateTestDomainRequest{} }
func (m *NewOrUpdateTestDomainRequest) String() string { return proto.CompactTextString(m) }
func (*NewOrUpdateTestDomainRequest) ProtoMessage()    {}
func (*NewOrUpdateTestDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *NewOrUpdateTestDomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrUpdateTestDomainRequest.Unmarshal(m, b)
}
func (m *NewOrUpdateTestDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrUpdateTestDomainRequest.Marshal(b, m, deterministic)
}
func (m *NewOrUpdateTestDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrUpdateTestDomainRequest.Merge(m, src)
}
func (m *NewOrUpdateTestDomainRequest) XXX_Size() int {
	return xxx_messageInfo_NewOrUpdateTestDomainRequest.Size(m)
}
func (m *NewOrUpdateTestDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrUpdateTestDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrUpdateTestDomainRequest proto.InternalMessageInfo

func (m *NewOrUpdateTestDomainRequest) GetNewOrUpdate() NewOrUpdateTestDomainUpdateType {
	if m != nil {
		return m.NewOrUpdate
	}
	return NewOrUpdateTestDomainUpdateType_New
}

func (m *NewOrUpdateTestDomainRequest) GetNewOrUpdateTestDomainData() *NewOrUpdateTestDomainData {
	if m != nil {
		return m.NewOrUpdateTestDomainData
	}
	return nil
}

type NewOrUpdateTestDomainData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Guid                 string   `protobuf:"bytes,2,opt,name=Guid,proto3" json:"Guid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	ReadyForUse          bool     `protobuf:"varint,5,opt,name=ReadyForUse,proto3" json:"ReadyForUse,omitempty"`
	Activated            bool     `protobuf:"varint,6,opt,name=Activated,proto3" json:"Activated,omitempty"`
	Deleted              bool     `protobuf:"varint,7,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	UpdateTimestamp      string   `protobuf:"bytes,8,opt,name=UpdateTimestamp,proto3" json:"UpdateTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrUpdateTestDomainData) Reset()         { *m = NewOrUpdateTestDomainData{} }
func (m *NewOrUpdateTestDomainData) String() string { return proto.CompactTextString(m) }
func (*NewOrUpdateTestDomainData) ProtoMessage()    {}
func (*NewOrUpdateTestDomainData) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *NewOrUpdateTestDomainData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrUpdateTestDomainData.Unmarshal(m, b)
}
func (m *NewOrUpdateTestDomainData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrUpdateTestDomainData.Marshal(b, m, deterministic)
}
func (m *NewOrUpdateTestDomainData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrUpdateTestDomainData.Merge(m, src)
}
func (m *NewOrUpdateTestDomainData) XXX_Size() int {
	return xxx_messageInfo_NewOrUpdateTestDomainData.Size(m)
}
func (m *NewOrUpdateTestDomainData) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrUpdateTestDomainData.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrUpdateTestDomainData proto.InternalMessageInfo

func (m *NewOrUpdateTestDomainData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NewOrUpdateTestDomainData) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *NewOrUpdateTestDomainData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewOrUpdateTestDomainData) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NewOrUpdateTestDomainData) GetReadyForUse() bool {
	if m != nil {
		return m.ReadyForUse
	}
	return false
}

func (m *NewOrUpdateTestDomainData) GetActivated() bool {
	if m != nil {
		return m.Activated
	}
	return false
}

func (m *NewOrUpdateTestDomainData) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *NewOrUpdateTestDomainData) GetUpdateTimestamp() string {
	if m != nil {
		return m.UpdateTimestamp
	}
	return ""
}

type NewOrUpdateTestDomainResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Guid                 string   `protobuf:"bytes,2,opt,name=Guid,proto3" json:"Guid,omitempty"`
	ResponseStatus       bool     `protobuf:"varint,3,opt,name=ResponseStatus,proto3" json:"ResponseStatus,omitempty"`
	ResponseMessage      string   `protobuf:"bytes,4,opt,name=ResponseMessage,proto3" json:"ResponseMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrUpdateTestDomainResponse) Reset()         { *m = NewOrUpdateTestDomainResponse{} }
func (m *NewOrUpdateTestDomainResponse) String() string { return proto.CompactTextString(m) }
func (*NewOrUpdateTestDomainResponse) ProtoMessage()    {}
func (*NewOrUpdateTestDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *NewOrUpdateTestDomainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrUpdateTestDomainResponse.Unmarshal(m, b)
}
func (m *NewOrUpdateTestDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrUpdateTestDomainResponse.Marshal(b, m, deterministic)
}
func (m *NewOrUpdateTestDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrUpdateTestDomainResponse.Merge(m, src)
}
func (m *NewOrUpdateTestDomainResponse) XXX_Size() int {
	return xxx_messageInfo_NewOrUpdateTestDomainResponse.Size(m)
}
func (m *NewOrUpdateTestDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrUpdateTestDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrUpdateTestDomainResponse proto.InternalMessageInfo

func (m *NewOrUpdateTestDomainResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NewOrUpdateTestDomainResponse) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *NewOrUpdateTestDomainResponse) GetResponseStatus() bool {
	if m != nil {
		return m.ResponseStatus
	}
	return false
}

func (m *NewOrUpdateTestDomainResponse) GetResponseMessage() string {
	if m != nil {
		return m.ResponseMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.MagicTableType", MagicTableType_name, MagicTableType_value)
	proto.RegisterEnum("api.MagicTableColumnDataType", MagicTableColumnDataType_name, MagicTableColumnDataType_value)
	proto.RegisterEnum("api.MagicTableColumnPresentationType", MagicTableColumnPresentationType_name, MagicTableColumnPresentationType_value)
	proto.RegisterEnum("api.NewOrUpdateTestDomainUpdateType", NewOrUpdateTestDomainUpdateType_name, NewOrUpdateTestDomainUpdateType_value)
	proto.RegisterType((*Instance)(nil), "api.Instance")
	proto.RegisterType((*Instances)(nil), "api.Instances")
	proto.RegisterType((*SearchRequest)(nil), "api.SearchRequest")
	proto.RegisterType((*TimeMessage)(nil), "api.TimeMessage")
	proto.RegisterType((*EmptyParameter)(nil), "api.EmptyParameter")
	proto.RegisterType((*MagicTableMetadataRequest)(nil), "api.MagicTableMetadataRequest")
	proto.RegisterType((*MagicTableMetadataRespons)(nil), "api.MagicTableMetadataRespons")
	proto.RegisterType((*MagicTableColumnMetadata)(nil), "api.MagicTableColumnMetadata")
	proto.RegisterType((*ListTestDomainRespons)(nil), "api.ListTestDomainRespons")
	proto.RegisterType((*ListTestDomainsRespons)(nil), "api.ListTestDomainsRespons")
	proto.RegisterType((*NewOrUpdateTestDomainRequest)(nil), "api.NewOrUpdateTestDomainRequest")
	proto.RegisterType((*NewOrUpdateTestDomainData)(nil), "api.NewOrUpdateTestDomainData")
	proto.RegisterType((*NewOrUpdateTestDomainResponse)(nil), "api.NewOrUpdateTestDomainResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 957 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xce, 0xda, 0xf5, 0xdf, 0x31, 0x71, 0x57, 0x03, 0x8d, 0x36, 0xa6, 0x0d, 0x66, 0xa1, 0x95,
	0x65, 0x4a, 0x12, 0x05, 0x09, 0x10, 0x5c, 0xa5, 0x75, 0x13, 0x22, 0x70, 0x88, 0xd6, 0x4e, 0x91,
	0xf8, 0x51, 0x34, 0xf6, 0x1e, 0x92, 0x11, 0xde, 0x9f, 0xec, 0x8c, 0x1b, 0xf9, 0x41, 0x78, 0x07,
	0x5e, 0x81, 0x7b, 0x9e, 0x82, 0x17, 0xe0, 0x09, 0xb8, 0xe0, 0x0e, 0xcd, 0xcc, 0x8e, 0xb3, 0xde,
	0xec, 0xb6, 0x5c, 0x73, 0xb7, 0xe7, 0x3b, 0xff, 0x67, 0xce, 0xcf, 0x42, 0x8b, 0xc6, 0x6c, 0x37,
	0x4e, 0x22, 0x11, 0x91, 0x2a, 0x8d, 0x99, 0xfb, 0xbb, 0x05, 0xcd, 0x93, 0x90, 0x0b, 0x1a, 0xce,
	0x90, 0x74, 0xa1, 0x79, 0x1e, 0xb2, 0xeb, 0x05, 0x9e, 0xf8, 0x8e, 0xd5, 0xb3, 0xfa, 0x55, 0x6f,
	0x45, 0x13, 0x02, 0xf7, 0x42, 0x1a, 0xa0, 0x53, 0xe9, 0x59, 0xfd, 0x96, 0xa7, 0xbe, 0xc9, 0x07,
	0xb0, 0xc9, 0x52, 0xdd, 0x0b, 0xb1, 0x8c, 0xd1, 0xa9, 0x2a, 0xe6, 0x5b, 0x06, 0x9c, 0x2c, 0x63,
	0x24, 0x36, 0x54, 0x71, 0xb6, 0x70, 0xee, 0xf5, 0xac, 0x7e, 0xc5, 0x93, 0x9f, 0x64, 0x0b, 0xea,
	0x01, 0x06, 0x51, 0xb2, 0x74, 0x6a, 0x0a, 0x4c, 0x29, 0xe2, 0x40, 0x23, 0x44, 0x71, 0x13, 0x25,
	0xbf, 0x38, 0x75, 0x65, 0xc8, 0x90, 0xe4, 0x1d, 0xa8, 0xc5, 0x09, 0x9b, 0xa1, 0xd3, 0x50, 0xb8,
	0x26, 0xdc, 0xcf, 0xa1, 0x65, 0x42, 0xe7, 0xe4, 0x23, 0x68, 0x19, 0xb7, 0xdc, 0xb1, 0x7a, 0xd5,
	0x7e, 0xfb, 0x60, 0x73, 0x57, 0x26, 0x6b, 0x44, 0xbc, 0x5b, 0xbe, 0xfb, 0x18, 0x36, 0xc7, 0x48,
	0x93, 0xd9, 0x95, 0x87, 0xd7, 0x0b, 0xe4, 0x42, 0x3a, 0xb8, 0x5e, 0x60, 0xb2, 0x54, 0x69, 0xb7,
	0x3c, 0x4d, 0xb8, 0x1f, 0x43, 0x7b, 0xc2, 0x02, 0x1c, 0x21, 0xe7, 0xf4, 0x12, 0xc9, 0x0e, 0x80,
	0x60, 0x01, 0x8e, 0x45, 0xc2, 0xc2, 0xcb, 0x54, 0x32, 0x83, 0xb8, 0x36, 0x74, 0x5e, 0x04, 0xb1,
	0x58, 0x9e, 0xd1, 0x84, 0x06, 0x28, 0x30, 0x71, 0xaf, 0x60, 0x7b, 0x44, 0x2f, 0xd9, 0x6c, 0x42,
	0xa7, 0x73, 0x1c, 0xa1, 0xa0, 0x3e, 0x15, 0xd4, 0xf8, 0xfc, 0x1a, 0xb6, 0xee, 0x32, 0x65, 0xc9,
	0x94, 0xe9, 0xce, 0xc1, 0xdb, 0x2a, 0xfc, 0x5b, 0x11, 0xc9, 0xf2, 0x4a, 0x54, 0xdc, 0xdf, 0xac,
	0x62, 0x57, 0x3c, 0x8e, 0x42, 0x4e, 0x7e, 0xc8, 0x32, 0x9f, 0x47, 0xf3, 0x45, 0x10, 0x72, 0x23,
	0x93, 0x16, 0xeb, 0x51, 0xce, 0x9b, 0x96, 0x5a, 0x19, 0x2a, 0xd7, 0x27, 0xbb, 0x40, 0x74, 0x31,
	0xa7, 0x34, 0x39, 0xe1, 0x2f, 0x19, 0x67, 0xd3, 0xb9, 0xee, 0x93, 0xa6, 0x57, 0xc0, 0x71, 0xff,
	0xac, 0x80, 0x53, 0xe6, 0x87, 0x0c, 0xc0, 0xd6, 0xc8, 0x57, 0x48, 0x7d, 0x4c, 0x4e, 0x65, 0xcb,
	0xe9, 0x4a, 0xdf, 0xc1, 0xc9, 0x13, 0xe8, 0x68, 0x6c, 0x48, 0x05, 0x3d, 0xbd, 0x6d, 0xce, 0x1c,
	0x4a, 0x5e, 0x64, 0xe5, 0x26, 0xa6, 0x4f, 0x3b, 0x25, 0x29, 0x1b, 0x21, 0x2f, 0xa7, 0x24, 0xa7,
	0x63, 0x1c, 0x25, 0x42, 0x4a, 0xaa, 0x6e, 0x6e, 0x7a, 0x2b, 0x9a, 0xfc, 0x04, 0x5b, 0x47, 0x51,
	0x12, 0x50, 0x71, 0x96, 0x20, 0xc7, 0x50, 0x50, 0xc1, 0xa2, 0x50, 0xb9, 0xaa, 0x29, 0x57, 0x8f,
	0x0b, 0x5d, 0xe5, 0x85, 0xbd, 0x12, 0x23, 0xa4, 0x0f, 0xf7, 0xc7, 0x57, 0xd1, 0x62, 0xee, 0x3f,
	0x43, 0x53, 0xdf, 0xba, 0x8a, 0x20, 0x0f, 0xbb, 0x7f, 0x5b, 0xf0, 0xe0, 0x1b, 0xc6, 0xc5, 0x04,
	0xb9, 0x18, 0x46, 0x01, 0x65, 0xa1, 0xe9, 0x81, 0x0e, 0x54, 0xd2, 0xb1, 0xae, 0x79, 0x15, 0x3d,
	0xd0, 0xc7, 0x0b, 0xe6, 0x9b, 0x81, 0x96, 0xdf, 0x12, 0x53, 0x75, 0xd4, 0x73, 0xac, 0xbe, 0x49,
	0x0f, 0xda, 0x43, 0xe4, 0xb3, 0x84, 0xc5, 0x32, 0x1c, 0x95, 0x79, 0xcb, 0xcb, 0x42, 0x52, 0xc2,
	0x43, 0xea, 0x2f, 0x8f, 0xa2, 0xe4, 0x9c, 0xeb, 0x8c, 0x9b, 0x5e, 0x16, 0x22, 0x0f, 0xa1, 0x75,
	0x38, 0x13, 0xec, 0x15, 0x15, 0xe8, 0xa7, 0x91, 0xdf, 0x02, 0x72, 0xee, 0x87, 0x38, 0x47, 0xc9,
	0x6b, 0x28, 0x9e, 0x21, 0x65, 0xde, 0xe7, 0xb1, 0x4f, 0x05, 0xca, 0x31, 0xe4, 0x82, 0x06, 0xb1,
	0xd3, 0x54, 0xfe, 0xf3, 0xb0, 0x1b, 0xc3, 0xd6, 0x7a, 0xda, 0xdc, 0xe4, 0xfd, 0x12, 0x9c, 0xd1,
	0xb2, 0x98, 0x97, 0xb6, 0x7e, 0x57, 0x3d, 0x4e, 0x61, 0xd5, 0xbc, 0x52, 0x5d, 0xf7, 0x0f, 0x0b,
	0x1e, 0x9e, 0xe2, 0xcd, 0xb7, 0x49, 0x1a, 0x4a, 0x46, 0x55, 0xcf, 0xf7, 0x11, 0xb4, 0x33, 0xfc,
	0x74, 0xa8, 0x3f, 0x54, 0xbe, 0x0a, 0xf5, 0x52, 0x5a, 0xf6, 0x41, 0x56, 0x91, 0xfc, 0x08, 0xdb,
	0x85, 0xf2, 0xb2, 0x31, 0xd5, 0xeb, 0xb5, 0x0f, 0x76, 0xca, 0xad, 0x0e, 0xd5, 0xf4, 0x96, 0xb2,
	0xdc, 0x7f, 0xac, 0xd7, 0x98, 0xff, 0x9f, 0x37, 0xcd, 0xaf, 0x16, 0x3c, 0x2a, 0x79, 0x42, 0xf5,
	0xc6, 0xf8, 0x9f, 0xf2, 0x7f, 0x02, 0x1d, 0x23, 0x3f, 0x16, 0x54, 0x2c, 0xb8, 0xaa, 0x44, 0xd3,
	0xcb, 0xa1, 0x32, 0x2e, 0x83, 0xa4, 0x17, 0x25, 0xad, 0x4b, 0x1e, 0x1e, 0x1c, 0x42, 0x67, 0x7d,
	0xed, 0x93, 0x4d, 0x68, 0xc9, 0xe8, 0x46, 0x91, 0x8f, 0x73, 0x7b, 0x83, 0xdc, 0x87, 0xb6, 0x0e,
	0x54, 0x03, 0x96, 0x04, 0xce, 0xe6, 0x8b, 0x4b, 0x03, 0x54, 0x06, 0x5f, 0xdc, 0xdd, 0xb1, 0xab,
	0x45, 0x06, 0x50, 0xd7, 0x17, 0xcb, 0xde, 0x20, 0x0d, 0xa8, 0x9e, 0x84, 0xc2, 0xb6, 0x48, 0x0b,
	0x6a, 0x47, 0xf3, 0x88, 0x0a, 0xbb, 0x32, 0xf8, 0x12, 0x7a, 0x6f, 0xda, 0x54, 0xca, 0x06, 0x0b,
	0xe2, 0x39, 0xda, 0x1b, 0xa4, 0x0d, 0x8d, 0x71, 0x9c, 0xb0, 0x50, 0xfc, 0x6c, 0x5b, 0x83, 0x4f,
	0xe1, 0xbd, 0x37, 0x74, 0xb7, 0xf4, 0x79, 0x8a, 0x37, 0xf6, 0x86, 0x34, 0xa2, 0x61, 0xdb, 0x3a,
	0xf8, 0xab, 0x02, 0xd5, 0xc3, 0x98, 0x91, 0xa7, 0x50, 0xd7, 0x37, 0x83, 0x10, 0xd5, 0xd4, 0x6b,
	0x77, 0xba, 0xdb, 0x59, 0x3b, 0xe9, 0x9c, 0xec, 0x43, 0xe3, 0x18, 0x85, 0x7c, 0x51, 0xa2, 0xcf,
	0xe5, 0xfa, 0x01, 0xee, 0xda, 0x0a, 0xcc, 0x1e, 0xf1, 0xef, 0xe0, 0xc1, 0x31, 0x8a, 0xbb, 0xa7,
	0x92, 0xec, 0xe4, 0x56, 0x74, 0xee, 0x5c, 0x77, 0xcb, 0xf9, 0x7a, 0xcf, 0x3c, 0x87, 0xfb, 0xb9,
	0x4d, 0x51, 0x1c, 0xd2, 0xbb, 0x05, 0xdb, 0x66, 0xb5, 0xac, 0xa6, 0xb0, 0x3d, 0xa6, 0xaf, 0xb0,
	0xb0, 0x82, 0xe4, 0xfd, 0xf2, 0x29, 0x37, 0x41, 0xba, 0xaf, 0x13, 0xd1, 0x4d, 0xf6, 0x6c, 0xf7,
	0xfb, 0xa7, 0xb3, 0xc0, 0xdf, 0xdb, 0xff, 0x6c, 0xff, 0xe2, 0xd0, 0xf7, 0x65, 0x20, 0x7a, 0x72,
	0x2e, 0x32, 0xf1, 0xec, 0xa9, 0x5f, 0x44, 0xbe, 0x47, 0x63, 0x36, 0xad, 0xab, 0xef, 0x4f, 0xfe,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x4b, 0xd9, 0xe8, 0x3b, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*Instances, error)
	GetTime(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*TimeMessage, error)
	GetMagicTableMetadata(ctx context.Context, in *MagicTableMetadataRequest, opts ...grpc.CallOption) (*MagicTableMetadataRespons, error)
	ListTestDomains(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*ListTestDomainsRespons, error)
	SaveNewOrUpdateTestDomain(ctx context.Context, in *NewOrUpdateTestDomainRequest, opts ...grpc.CallOption) (*NewOrUpdateTestDomainResponse, error)
}

type apiClient struct {
	cc *grpc.ClientConn
}

func NewApiClient(cc *grpc.ClientConn) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*Instances, error) {
	out := new(Instances)
	err := c.cc.Invoke(ctx, "/api.Api/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetTime(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*TimeMessage, error) {
	out := new(TimeMessage)
	err := c.cc.Invoke(ctx, "/api.Api/GetTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetMagicTableMetadata(ctx context.Context, in *MagicTableMetadataRequest, opts ...grpc.CallOption) (*MagicTableMetadataRespons, error) {
	out := new(MagicTableMetadataRespons)
	err := c.cc.Invoke(ctx, "/api.Api/GetMagicTableMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ListTestDomains(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*ListTestDomainsRespons, error) {
	out := new(ListTestDomainsRespons)
	err := c.cc.Invoke(ctx, "/api.Api/ListTestDomains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SaveNewOrUpdateTestDomain(ctx context.Context, in *NewOrUpdateTestDomainRequest, opts ...grpc.CallOption) (*NewOrUpdateTestDomainResponse, error) {
	out := new(NewOrUpdateTestDomainResponse)
	err := c.cc.Invoke(ctx, "/api.Api/SaveNewOrUpdateTestDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
type ApiServer interface {
	Search(context.Context, *SearchRequest) (*Instances, error)
	GetTime(context.Context, *EmptyParameter) (*TimeMessage, error)
	GetMagicTableMetadata(context.Context, *MagicTableMetadataRequest) (*MagicTableMetadataRespons, error)
	ListTestDomains(context.Context, *EmptyParameter) (*ListTestDomainsRespons, error)
	SaveNewOrUpdateTestDomain(context.Context, *NewOrUpdateTestDomainRequest) (*NewOrUpdateTestDomainResponse, error)
}

// UnimplementedApiServer can be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (*UnimplementedApiServer) Search(ctx context.Context, req *SearchRequest) (*Instances, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedApiServer) GetTime(ctx context.Context, req *EmptyParameter) (*TimeMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTime not implemented")
}
func (*UnimplementedApiServer) GetMagicTableMetadata(ctx context.Context, req *MagicTableMetadataRequest) (*MagicTableMetadataRespons, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMagicTableMetadata not implemented")
}
func (*UnimplementedApiServer) ListTestDomains(ctx context.Context, req *EmptyParameter) (*ListTestDomainsRespons, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTestDomains not implemented")
}
func (*UnimplementedApiServer) SaveNewOrUpdateTestDomain(ctx context.Context, req *NewOrUpdateTestDomainRequest) (*NewOrUpdateTestDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveNewOrUpdateTestDomain not implemented")
}

func RegisterApiServer(s *grpc.Server, srv ApiServer) {
	s.RegisterService(&_Api_serviceDesc, srv)
}

func _Api_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetTime(ctx, req.(*EmptyParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetMagicTableMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MagicTableMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetMagicTableMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/GetMagicTableMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetMagicTableMetadata(ctx, req.(*MagicTableMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ListTestDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ListTestDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/ListTestDomains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ListTestDomains(ctx, req.(*EmptyParameter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SaveNewOrUpdateTestDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewOrUpdateTestDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).SaveNewOrUpdateTestDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Api/SaveNewOrUpdateTestDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).SaveNewOrUpdateTestDomain(ctx, req.(*NewOrUpdateTestDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Api_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Api_Search_Handler,
		},
		{
			MethodName: "GetTime",
			Handler:    _Api_GetTime_Handler,
		},
		{
			MethodName: "GetMagicTableMetadata",
			Handler:    _Api_GetMagicTableMetadata_Handler,
		},
		{
			MethodName: "ListTestDomains",
			Handler:    _Api_ListTestDomains_Handler,
		},
		{
			MethodName: "SaveNewOrUpdateTestDomain",
			Handler:    _Api_SaveNewOrUpdateTestDomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
